Analytics & Data Science

Universidad de Antioquia - ML2

Febrero 2024

Melissa Ortega Alzate CC.1036964792

# Libraries

In [71]:
import numpy as np

# Paso 1

In [72]:
# Step 1. Randomly initializing K centroid by picking K samples from X
def initialize_random_centroids(K, X):
    """Initializes and returns k random centroids"""
    
    m, n = np.shape(X)
    
    # Initializate empty centroids variable with (K, n) shape
    centroids = np.empty((K, n))

    for i in range(K):
        # pick a random data point from X as the centroid
        centroids[i] =  X[np.random.choice(range(m))] 
    return centroids

In [73]:
X = np.random.rand(3,5)
K =4
X

array([[0.62354407, 0.85563254, 0.75774498, 0.15996691, 0.26329512],
       [0.40045384, 0.48763152, 0.18664324, 0.92585266, 0.01341561],
       [0.68655395, 0.77499034, 0.44183525, 0.02352377, 0.23401701]])

In [74]:
centroids = initialize_random_centroids(K, X)
centroids

array([[0.40045384, 0.48763152, 0.18664324, 0.92585266, 0.01341561],
       [0.40045384, 0.48763152, 0.18664324, 0.92585266, 0.01341561],
       [0.40045384, 0.48763152, 0.18664324, 0.92585266, 0.01341561],
       [0.62354407, 0.85563254, 0.75774498, 0.15996691, 0.26329512]])

# Paso 2

In [75]:
# Calculate the distance between two vectors
def euclidean_distance(x1, x2):
    """Calculates and returns the euclidean distance between two vectors x1 and x2"""
    return np.linalg.norm(x1 - x2)

In [76]:
# Step 2. 
def closest_centroid(x, centroids, K):
    """Finds and returns the index of the closest centroid for a given vector x"""
    distances = np.empty(K)

    for i in range(K):
        distances[i] = euclidean_distance(centroids[i], x)
    return np.argmin(distances) # return the index of the lowest distance

In [77]:
def closest_centroid(x, centroids, K):
    """Finds and returns the index of the closest centroid for a given vector x"""
    distances = np.empty(K)
    
    for i in range(K):
        distances[i] = euclidean_distance(centroids[i], x)
    return np.argmin(distances) # return the index of the lowest distance

In [78]:
closest_centroid = closest_centroid(X[1,1], centroids, K)
closest_centroid

3

In [81]:
centroids[closest_centroid]

array([0.62354407, 0.85563254, 0.75774498, 0.15996691, 0.26329512])

In [80]:
# kmeans implementar sólo fit and predict

In [ ]:
# fit: data de entrenamiento
# hasta encontrar los clusters
# return clusters

In [ ]:
# predict para kmeans: data de prueba
# - calcular la distancia de cada dato nuevo a los clusters ya creados

In [ ]:
# swaping para k-medoids en vez de np.median