In [72]:
# Librerías
import numpy as np

1. Simulate any random rectangular matrix A

In [73]:
A = np.random.rand(3,5)
A

array([[0.11906251, 0.55077125, 0.48064423, 0.45225558, 0.68252206],
       [0.0946479 , 0.32238215, 0.54125639, 0.57816733, 0.77510856],
       [0.46980143, 0.17661246, 0.94671317, 0.15196672, 0.51326632]])

In [74]:
# 1.1  What is the rank and trace of A?
print(f'The rank of A matrix is: ', np.linalg.matrix_rank(A))
print(f'The trace of A matrix is: ', np.trace(A))

The rank of A matrix is:  3
The trace of A matrix is:  1.3881578319105263


In [75]:
# 1.2 What is the determinant of A?
# print(f'The determinant of A matrix is: ', np.linalg.det(A))

print('LinAlgError: Last 2 dimensions of the array must be square')

LinAlgError: Last 2 dimensions of the array must be square


In [76]:
# 1.3 Can you invert A? How?

# print(f'The inverse of A matrix is: \n', np.linalg.inv(A))
A_inverse = np.linalg.pinv(A)
print(f'The pseudo-inverse of A matrix is: \n\n', A_inverse)

# inv: lineal no se puede porque no es cuadrada ni tiene determinante
# p: calcula una pseudoinversa con pérdida computacional

The pseudo-inverse of A matrix is: 

 [[ 3.22469448e-01 -8.25270029e-01  7.29020741e-01]
 [ 3.48920301e+00 -2.79122004e+00 -2.36145358e-01]
 [-4.11015251e-01  3.18790618e-03  9.51718518e-01]
 [-1.03575249e+00  1.86657508e+00 -5.82941588e-01]
 [-4.31004060e-01  1.15729773e+00 -2.20559012e-01]]


In [95]:
# Calculating A_T
A_T = np.transpose(A)
A_T

array([[0.11906251, 0.0946479 , 0.46980143],
       [0.55077125, 0.32238215, 0.17661246],
       [0.48064423, 0.54125639, 0.94671317],
       [0.45225558, 0.57816733, 0.15196672],
       [0.68252206, 0.77510856, 0.51326632]])

In [91]:
# 1.4 How are eigenvalues and eigenvectors

# Eigen values and vector of AA_T
eigenvalues, eigenvectors = np.linalg.eig(A @ A_T)
print('The eigenvalues of A * A_T : \n', eigenvalues)
print('\n The eigenvectors of A * A_T : \n', eigenvectors)

The eigenvalues of A * A_T : 
 [3.57751397 0.03851868 0.37850763]

 The eigenvectors of A * A_T : 
 [[-0.56262067 -0.71170458 -0.42063592]
 [-0.59430898  0.70187671 -0.39263968]
 [-0.57467802 -0.0290805   0.81786276]]


In [93]:
# 1.4 How are eigenvalues and eigenvectors

# Eigen values and vector of A_T*A
eigenvalues, eigenvectors = np.linalg.eig(A_T @ A)

print('The eigenvalues of A_T * A : \n', eigenvalues)
print('\n The eigenvalues of A_T * A : \n', eigenvectors)

The eigenvalues of A_T * A : 
 [ 3.57751397e+00  3.78507626e-01  3.85186810e-02 -9.19358801e-17
  1.20583273e-16]

 The eigenvalues of A_T * A : 
 [[-0.20789631 -0.48272798  0.1628857  -0.80503281 -0.03423418]
 [-0.31878771  0.34752781  0.87052042  0.01145829 -0.13005597]
 [-0.60068209 -0.58447515 -0.05241808  0.39134268 -0.2392066 ]
 [-0.36236587  0.47617733 -0.40512503 -0.42421375 -0.649097  ]
 [-0.60251599  0.2790019  -0.22088121  0.1366912   0.70948344]]


# 2. ADD


In [117]:
import cv2

In [118]:
# Análisis exploratorio de las imágenes
im = cv2.imread("melissa.jpeg")

# Definir parámetros
img_shape = im.shape
img_size = (im.shape[0], im.shape[1])
channels = im.shape[2]
color = 'rgb'

# Imprimir características de la imágen aleatoria
print(f"El tamaño de la figura es: {img_size} pixeles" )
print(f"La figura tiene: {channels} canales")
print(f"La figuras es de tipo: {im.dtype}")
print(f"La figura tiene pixeles en el rango: {im.min()} - {im.max()}")

El tamaño de la figura es: (194, 259) pixeles
La figura tiene: 3 canales
La figuras es de tipo: uint8
La figura tiene pixeles en el rango: 0 - 255


In [120]:
im = cv2.resize(im, (254,254))


array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]